#!/bin/bash
# Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found
# in the LICENSE file.
#
# This script creates QNX-specific CEF project files by:
# 1. Applying QNX-specific patches from cef/patch/patches/qnx/
# 2. Setting up QNX-specific GN arguments
# 3. Running gn gen with QNX toolchain

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CEF_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
CHROMIUM_SRC_DIR="$(cd "${CEF_DIR}/.." && pwd)"

# Default values
BUILD_TYPE="Release"
QNX_SDP_ROOT="${QNX_SDP_ROOT:-$HOME/qnx800}"
QNX_TARGET="${QNX_TARGET:-qnx}"  # or "qnx-sdp8"

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --build-type)
      BUILD_TYPE="$2"
      shift 2
      ;;
    --qnx-sdp-root)
      QNX_SDP_ROOT="$2"
      shift 2
      ;;
    --qnx-target)
      QNX_TARGET="$2"
      shift 2
      ;;
    --help)
      echo "Usage: $0 [options]"
      echo ""
      echo "Options:"
      echo "  --build-type <type>     Build type: Debug or Release (default: Release)"
      echo "  --qnx-sdp-root <path>   QNX SDP installation root (default: ~/qnx800)"
      echo "  --qnx-target <target>   QNX target: qnx or qnx-sdp8 (default: qnx)"
      echo "  --help                  Show this help message"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Validate QNX SDP installation
if [[ ! -d "${QNX_SDP_ROOT}/target/qnx" ]]; then
  echo "ERROR: QNX SDP not found at ${QNX_SDP_ROOT}"
  echo "Please set QNX_SDP_ROOT environment variable or use --qnx-sdp-root"
  exit 1
fi

echo "CEF QNX Project Creator"
echo "======================="
echo "Build type: ${BUILD_TYPE}"
echo "QNX SDP: ${QNX_SDP_ROOT}"
echo "QNX Target: ${QNX_TARGET}"
echo ""

# Step 1: Install new QNX platform files
echo "Step 1: Installing new QNX platform files..."
NEW_FILES_DIR="${CEF_DIR}/patch/qnx/chromium/new_files"
if [[ -d "${NEW_FILES_DIR}" ]]; then
  while IFS= read -r -d '' file; do
    rel_path="${file#${NEW_FILES_DIR}/}"
    target_file="${CHROMIUM_SRC_DIR}/${rel_path}"
    if [[ ! -f "${target_file}" ]]; then
      echo "  Installing: ${rel_path}"
      mkdir -p "$(dirname "${target_file}")"
      cp "${file}" "${target_file}"
    else
      echo "  Skipping (exists): ${rel_path}"
    fi
  done < <(find "${NEW_FILES_DIR}" -type f -print0)
fi
echo ""

# Step 2: Apply QNX-specific patches
echo "Step 2: Applying QNX-specific patches..."
"${SCRIPT_DIR}/patcher.py" --patch-file qnx/googletest_death_test || true
"${SCRIPT_DIR}/patcher.py" --patch-file qnx/perfetto_aggregate_init || true
"${SCRIPT_DIR}/patcher.py" --patch-file qnx/perfetto_mincore || true

# Apply additional QNX patches from cef/patch/patches/qnx/chromium/
if [[ -d "${CEF_DIR}/patch/patches/qnx/chromium" ]]; then
  echo "Applying Chromium QNX patches..."
  for patch_file in "${CEF_DIR}/patch/patches/qnx/chromium"/*.patch; do
    if [[ -f "$patch_file" ]]; then
      patch_name="$(basename "$patch_file" .patch)"
      echo "  - ${patch_name}"
      "${SCRIPT_DIR}/patcher.py" --patch-file "qnx/chromium/${patch_name}" || true
    fi
  done
fi

echo ""

# Step 2: Set up build directory
BUILD_DIR="${CHROMIUM_SRC_DIR}/out/qnx_${BUILD_TYPE,,}"
mkdir -p "${BUILD_DIR}"

echo "Step 2: Build directory: ${BUILD_DIR}"
echo ""

# Step 3: Create GN args file
echo "Step 3: Creating GN args..."

GN_ARGS_FILE="${BUILD_DIR}/args.gn"
cat > "${GN_ARGS_FILE}" << EOF
# QNX-specific GN args for CEF
# Auto-generated by cef_create_projects_qnx.sh

# Target OS and architecture
target_os = "qnx"
target_cpu = "x64"

# Build type
is_debug = $([[ "$BUILD_TYPE" == "Debug" ]] && echo "true" || echo "false")
is_component_build = false
is_official_build = $([[ "$BUILD_TYPE" == "Release" ]] && echo "true" || echo "false")

# QNX toolchain
qnx_sdp_root = "${QNX_SDP_ROOT}"
qnx_target = "${QNX_TARGET}"

# Disable features not supported on QNX
enable_print_preview = false
enable_widevine = false
enable_nacl = false
enable_mdns = false

# CEF specific
cef_target_arch = "x64"
cef_use_alloc_shim = false

# Compiler settings (QNX uses QCC which is Clang-based)
is_clang = true
treat_warnings_as_errors = false

# Disable sandbox (not supported on QNX)
cef_enable_sandbox = false

# Test settings (for base_unittests)
enable_base_tracing = false

# QNX-specific overrides
use_qt = false
use_ozone = false
use_x11 = false
use_glib = false
use_gio = false
use_udev = false
use_system_libffi = false
EOF

echo "GN args written to: ${GN_ARGS_FILE}"
echo ""

# Step 4: Run gn gen
echo "Step 4: Running gn gen..."
cd "${CHROMIUM_SRC_DIR}"

# Set up environment for gn
export QNX_SDP_ROOT
export QNX_TARGET

# Run gn gen
gn gen "${BUILD_DIR}" --args="$(cat "${GN_ARGS_FILE}" | tr '\n' ' ')"

echo ""
echo "Success! QNX CEF project files created."
echo ""
echo "Build directory: ${BUILD_DIR}"
echo ""
echo "To build:"
echo "  cd ${CHROMIUM_SRC_DIR}"
echo "  ninja -C ${BUILD_DIR} cef"
echo ""
